"""Machine-checked writing conventions, run in CI and before finishing.

Blocking: em and en dashes, emoji, AI attribution strings, live credential
shapes. Flagged for review, not blocked: the words "solves", "blocks" and
"prevents", which a regex cannot judge ("CI blocks regressions" is fine;
"the gateway blocks prompt injection" is the claim this portfolio exists to
stop making).

    uv run python scripts/check_conventions.py
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

DASHES = "\u2013\u2014"

EMOJI_RANGES = (
    (0x1F300, 0x1FAFF),
    (0x2600, 0x27BF),
    (0x2B00, 0x2BFF),
    (0xFE0F, 0xFE0F),
)

ATTRIBUTION = (
    "co-authored-by",
    "generated with",
    "generated by claude",
    "claude",
    "anthropic",
    "codex",
    "chatgpt",
    "openai code",
)

CREDENTIAL_PATTERNS = (
    re.compile(r"sk-[A-Za-z0-9]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"ghp_[A-Za-z0-9]{30,}"),
    re.compile(r"xoxb-[A-Za-z0-9-]{20,}"),
    re.compile(r"://[^/\s:]+:[^@\s]+@", flags=re.I),
)

REVIEW_WORDS = re.compile(r"\b(solves|blocks|prevents)\b", flags=re.I)


def tracked_files() -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z"], capture_output=True, text=True, check=True
    )
    return [f for f in result.stdout.split("\0") if f]


def is_emoji(char: str) -> bool:
    code = ord(char)
    return any(lo <= code <= hi for lo, hi in EMOJI_RANGES)


def scan(path: str) -> tuple[list[str], list[str]]:
    blocking: list[str] = []
    review: list[str] = []
    if path.replace("\\", "/") == "scripts/check_conventions.py":
        # The only file that must quote the banned markers is the one that
        # lists them.
        return blocking, review
    try:
        text = Path(path).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return blocking, review
    for lineno, line in enumerate(text.splitlines(), 1):
        where = f"{path}:{lineno}"
        if any(d in line for d in DASHES):
            blocking.append(f"{where}: em or en dash")
        if any(is_emoji(c) for c in line):
            blocking.append(f"{where}: emoji")
        lowered = line.lower()
        for marker in ATTRIBUTION:
            if marker in lowered:
                blocking.append(f"{where}: attribution marker {marker!r}")
                break
        for pattern in CREDENTIAL_PATTERNS:
            if pattern.search(line):
                blocking.append(f"{where}: possible credential ({pattern.pattern})")
                break
        if REVIEW_WORDS.search(line) and not path.endswith(".py"):
            review.append(f"{where}: {REVIEW_WORDS.search(line).group(0)}")
    return blocking, review


def main() -> int:
    failures: list[str] = []
    notes: list[str] = []
    for path in tracked_files():
        blocking, review = scan(path)
        failures.extend(blocking)
        notes.extend(review)
    for note in notes[:20]:
        print(f"review: {note}")
    if notes:
        print(f"{len(notes)} line(s) flagged for human review, not blocked")
    for failure in failures:
        print(f"FAIL: {failure}")
    if failures:
        print(f"\n{len(failures)} convention violation(s)")
        return 1
    print("conventions clean")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
